### ISSUE TITLE
[DOCUMENTATION] update documentation to reflect newer version and changes since the beta version

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/opensearch-plugin-template-java#17]
**What is the bug?**
The version this template is based on is v1.0.0-beta should update to 1.2.3 if only to discourage the use of this in older log4shell-vulnerable projects.

**What is the expected behavior?**
Updated documentation

**Comment by AmiStrn** [comment]
Waiting for [this pr](https://github.com/opensearch-project/opensearch-plugin-template-java/pull/16) to be done merged before beginning work on this

**Comment by dblock** [comment]
This was done.
