### ISSUE TITLE
[BUG] OpenSearch version explicitly specified in CI.yml file

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/opensearch-plugin-template-java#21]
**What is the bug?**

Currently, the [CI.yml](https://github.com/opensearch-project/opensearch-plugin-template-java/blob/a36777fea4c364e5efa5e3770ad33967f169eebd/.github/workflows/CI.yml#L32) file explicitly specify `opensearch.version` property. Interestingly, as of writing it slightly differs from the version specified in [`build.gradle`](https://github.com/opensearch-project/opensearch-plugin-template-java/blob/a36777fea4c364e5efa5e3770ad33967f169eebd/build.gradle#L40).

My questions are:
- Is there any benefit in specifying opensearch version in CI file? Is it not enough that opensearch version is actually specified in `build.gradle` file?
- Does it mean that plugin authors maybe interested in running their CI workflow against different version of opensearch than what their build script depends on? And if there is such a case shouldn't it be documented so that plugin authors know how and when to specify different versions?

**Comment by dblock** [comment]
FYI we let you specify `-Dopensearch.version` to allow building for a different distribution at the same time since all versions have to match (e.g. `1.3.0-SNAPSHOT` vs. `1.3.0`). So no need to have it in the CI yml, thanks for the change!

**Comment by lukas-vlcek** [comment]
> we let you specify -Dopensearch.version to allow building for a different distribution at the same time since all versions have to match (e.g. 1.3.0-SNAPSHOT vs. 1.3.0)

@dblock Do you if this is documented? Would be nice to have it into the docs along with some explanation.

**Comment by dblock** [comment]
> > we let you specify -Dopensearch.version to allow building for a different distribution at the same time since all versions have to match (e.g. 1.3.0-SNAPSHOT vs. 1.3.0)
> 
> @dblock Do you know if this is documented anywhere? Would be nice to have it in the docs along with some explanation.

I think we could add something to https://github.com/opensearch-project/opensearch-build/blob/main/src/build_workflow/README.md regarding this. Want to give that doc a read and maybe PR something?

**Comment by dblock** [comment]
Actually we do document this in https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#always-build-snapshot-artifacts.
