### ISSUE TITLE
Move repo to opensearch-project

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugin-template-java#4]
I propose to rename this to `opensearch-plugin-template` and move to the OpenSearch organization.

**Comment by AmiStrn** [comment]
Since I'm not a maintainer I would be happy to get some help with the move + making the repo be a template repo.

**Comment by AmiStrn** [comment]
renamed

**Comment by dblock** [comment]
👍 flagging for @CEHENKLE to move this into opensearch-project, retaining @AmiStrn as admin

**Comment by dblock** [comment]
Found another repo like this, https://github.com/ketanv3/opensearch-plugin-boilerplate. So `opensearch-plugin-template` should probably be `opensearch-plugin-template-java`.

**Comment by AmiStrn** [comment]
The rename suggestion is fine. Also, it's nice to see it in kotlin as well:)
Though, this other repo is not offering the same level of readiness to those who use it. I'll reach out to the person maintaining it. We should have the same standard for the templates.

**Comment by dblock** [comment]
> We should have the same standard for the templates.

True. But when one has a higher standard the other one tries to catch up :)

**Comment by dblock** [comment]
We are ready to move forward with this! @AmiStrn sent you an email, cc-ing @hyandel who will help with the logistics.

**Comment by hyandell** [comment]
Repository transferred :)

**Comment by AmiStrn** [comment]
The issue has been resolved - thanks @hyandell and @dblock for handling this:)
