### ISSUE TITLE
[BUG] OpenSearch version: 1.3.6,  Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.

### ISSUE THREAD

**Issue by know-no** [opensearch-project/opensearch-plugin-template-java#41]
### What is the bug?
I am trying to develop my own OpenSearch Plugin, which generated from the template project. When building the project, something went wrong with version 1.3.6.

opensearch.version  -> 1.3.6

`./gradlew build`

A problem occurred evaluating root project 'opensearch-tenant'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation

### How can one reproduce the bug?

1. open the link:  https://github.com/opensearch-project/opensearch-plugin-template-java
2. use this template
3. clone the new project
4. modify `build.gradle`, jump to line 63,  change opensearch.version to 1.3.6
5. run `./gradlew build`
6. something goes wrong

### What is the expected behavior?
Nothing bad happend with verions: 2.x and 3.x 

### What is your host/environment?
macOS. Monterey 12.5.1
jvm:  corretto-11.0.14
ide:  IntelliJ IDEA 2022.1.4 (Community Edition) Build #IC-221.6008.13, built on July 19, 2022

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/21367421/197709198-2c09a729-ab25-4e59-9b32-1b82745d201b.png)

### Do you have any additional context?
No

**Comment by AmiStrn** [comment]
Looks like the template is gonna need to be versioned. Could save time and effort for users.@dblock wdyt? Valid solution?

**Comment by AmiStrn** [comment]
@dblock yes, i agree.
Going to take the lazy approach here, i will make a label for 1.1, a label for when build works with 1.3.6, and then 2.x (and main tracks 3.x).

Adding labels later for each version will make it less copy pasty too.

**Comment by AmiStrn** [comment]
@know-no in the meantime, if can you build the plugin from an earlier commit in this repo from before the breaking change was made, then you wouldnt have to wait for my change.

**Comment by know-no** [comment]
@AmiStrn Ok, thank you ~. I will try. If it doesn't work, i will wait.

**Comment by know-no** [comment]
I works at commit: 2d5ee08f083cda3337098fcce7e58dc461ce8bce

**Comment by know-no** [comment]
> @know-no in the meantime, if can you build the plugin from an earlier commit in this repo from before the breaking change was made, then you wouldnt have to wait for my change.
> 
> There are not that many commits, so it shouldnt be difficult. If this doesn't work then you would need to wait for the versioning fix.

It works at 2d5ee08f083cda3337098fcce7e58dc461ce8bce.  But `./settings.gradle` and `./build.gradle` still need some change: 
![image](https://user-images.githubusercontent.com/21367421/198198561-060ea806-a137-4f64-9253-6e65325da979.png)
![image](https://user-images.githubusercontent.com/21367421/198198626-00daaa2e-0101-49a5-9460-264cbcae3c6c.png)

**Comment by dblock** [comment]
We have backport branches such as 2.x for this. Closing.
