### ISSUE TITLE
[PROPOSAL] Delete the manual DCO check

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/opensearch-plugin-template-java#61]
### What are you proposing?
currently, this repository is using the GH action workflow `dco.yml` to verify that a sign-off is provided. nowadays, this can be controlled directly via GitHub settings (see [the GH documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)).
for OpenSearch this has already been changed a year ago by @VachaShah in https://github.com/opensearch-project/OpenSearch/pull/2317

if this is done it should also be documented that the same needs to be done on repositories started off of this template (presuming they want the DCO).

### What users have asked for this feature?
n/a

### What problems are you trying to solve?
align repositories, use standard features of GitHub.

### What is the developer experience going to be?
n/a

#### Are there any security considerations? 
n/a

#### Are there any breaking changes to the API
n/a

### What is the user experience going to be?
n/a

#### Are there breaking changes to the User Experience?
n/a

### Why should it be built? Any reason not to?
n/a

### What will it take to execute?
* admin user to set the setting on the GH repo
* PR to remove the DCO workflow

### Any remaining open questions?
n/a

**Comment by dblock** [comment]
We have a DCO bot enabled for the org. The manual DCO check can be deleted.
