### ISSUE TITLE
enable automatic backport to 2.x

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/opensearch-plugin-template-java#75]
since we now have a `2.x` branch here (since #69) it'd be good if the automated backport bot would be set up the same way as for the other opensearch repos (i'm not familiar with the details - i just know that it exists 😄) to ensure that 2.x is kept in sync where relevant.

until this is the case cherry-picks will have to be done manually.

**Comment by dblock** [comment]
@rursprung You can just copy the backport workflow from maybe https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/backport.yml

**Comment by rursprung** [comment]
> @rursprung You can just copy the backport workflow from maybe https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/backport.yml
> 
> #83

i guess this has to be done by a maintainer with admin access as you need to set up the secrets? thus i will refrain from contributing this as it presumably won't work
