### ISSUE TITLE
[PROPOSAL] Lower the number of required approvers to 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugin-template-java#84]
### What are you proposing?

Currently every PR in this repo requires 2 approvers. Lower it to 1.

### What problems are you trying to solve?

This is not a critical path repo where we need two pairs of eyes for each change. Let's go faster.

![Screenshot 2024-06-11 at 10 11 25 AM](https://github.com/opensearch-project/opensearch-plugin-template-java/assets/542335/cee1cf26-45b6-45b0-ba66-03b919790761)

If 2/3 of the maintainers agree, I can make the change on GitHub, cc: @reta @AmiStrn @saratvemulapalli

**Comment by AmiStrn** [comment]
made the change 👍
