### ISSUE TITLE
Lower CI Java Version to Java 11 for all plugins and run integration tests on 8

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/opensearch-plugin-template-java#9]
(Copy of https://github.com/opensearch-project/opensearch-plugins/issues/64)

We lowered the version of Java to 11 for OpenSearch in opensearch-project/opensearch-build#74. In the documentation we say:

> We recommend Java 11 (LTS), but OpenSearch also works with Java 8.

- [ ] Lower the Java version for CI to 11 (use LTS)
- [ ] Run integration tests on at least Java 8 and 11 (ensure broad compatibility)
- [ ] Document that the preferred version of Java for development is 14 (do development on latest and greatest)

**Comment by dblock** [comment]
Will require newer OpenSearch, currently JDK 11 build would fail with this in integration tests:

```
Error: LinkageError occurred while loading main class org.opensearch.gradle.reaper.Reaper
        java.lang.UnsupportedClassVersionError: org/opensearch/gradle/reaper/Reaper has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by AmiStrn** [comment]
In that case ill close this:)

**Comment by AmiStrn** [comment]
awaiting a newer OpenSearch. keeping this open for later:)

**Comment by dblock** [comment]
Let's scrap this and just move forward to 17 and OpenSearch 2.0.
